name: IgniteLeveling
version: '1.0.0'
main: com.ignitedev.igniteLeveling.IgniteLeveling
api-version: '1.21'
authors: [ IgniteDEV ]
description: Leveling and Statistics for players
website: https://github.com/IM-IgniteDEV/
softdepend: ["PlaceholderAPI"]